export const AuthErrors = {
  MISSING_FIELDS: "MISSING_FIELDS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INVALID_OTP: "INVALID_OTP",
  OTP_EXPIRED: "OTP_EXPIRED",
  USER_ALREADY_VERIFIED: "USER_ALREADY_VERIFIED",
  SERVER_ERROR: "SERVER_ERROR",
} as const;
